### PR TITLE
do not start ensime server is it is already running externally

### PR DESCRIPTION
**Pull request by kstep**
I run ensime server manually for my projects with systemd user unit, so I don't need to (re)start it every time I restart vim.

This patch allows me to re-use already existing server.

### CODE REVIEW

**Comment by kstep** [comment]
The second commit fixes an error for me: when I use `:EnDeclaration` new buffer with Scala file is opened OK, but its filetype is unset, so I don't get syntax highlighting etc.

**Comment by jvican** [comment]
Cool, @kstep, I was about to report the bug of `:EnDeclaration`.

**Comment by yazgoo** [comment]
Thanks,
On vim:
I'm getting this error when running EnDocUri

````
E605: Exception not caught: <type 'exceptions.TypeError'>:cannot concatenate 'str' and 'int' objects
````

I'm also getting `Using list as number` when trying autocomplete.

**Comment by kstep** [comment]
Could you give me a choice snippet you use ensime-vim on to get such results? Thank you.

**Comment by yazgoo** [comment]
I'm using this project:
https://github.com/pocorall/scaloid/ running:

vim src/scaloid/example/HelloScaloid.scala

**Comment by yazgoo** [comment]
Again thanks for your work :+1: 
Looks like you're editing autoload file which is a generated file, via https://github.com/yazgoo/neo2vim/pulls see developer howto https://github.com/ensime/ensime-vim/blob/master/README.md

**Comment by kstep** [comment]
Thanks for pointers! I cleaned up things a little, updated file in rpython and regenerated autoload part.
It should look better now.

**Comment by kstep** [comment]
To sum things up, this PR now has the changed:

- re-use existing ensime server if it's already listening,
- EnDeclaration filetype setup fix
- autocompletion fixes

**Pull request merged**
