### PR TITLE
Use a proper S-expression parser for .ensime

### PR DESCRIPTION
**Pull request by ches**
This uses [a real S-expression parser][1] for `.ensime`, hopefully a step toward being more robust for the output of other build tools like Gradle (see #194).

This is just a sketch to get feedback on the idea—since `sexpdata` is a reasonably small module that's self-contained in a single file, and its license allows it, I just vendored the source code so we don't have to ask users to `pip install` another dependency. But of course I'm open to feedback on that.

It'd be nice to organize the nested functions somewhere or maybe make an `EnsimeConfig` dict wrapper class or something for them—that's why I've preemptively made separate functions with docstrings—but I can go further with the organization after getting your thoughts.

/cc @codyrioux

- [ ] Refactor the `disable_plugin` machinery from `EnsimeClient` to be usable in launcher
- [ ] Update documentation site to add `sexpdata` to the pip installs

[1]: https://github.com/tkf/sexpdata

### CODE REVIEW

**Comment by ches** [comment]
By the way, my recursive dict-transforming is fairly quick and dirty—if the unit tests were working currently it'd be nice to test a few normal `.ensime` and funkier S-expression structures… I'll try to get around to getting unit tests going again too, but in the meantime if folks can try this with a few different project `.ensime`s and build tool plugins that'd be a good place to start as far as more testing goes.

**Comment by ChrisCoffey** [comment]
Great idea, I'll give this a look tonight

**Comment by ChrisCoffey** [comment]
I would rather use the pip requirements file than vendor the code. That way it's still just one thing for users to run. 

If it feels to difficult to ask people to run `pip install -r <path-to-plugin>/requirements.txt` then we could go so far as to bootstrap the install.

**Comment by jvican** [comment]
Thanks for bringing this @ChrisCoffey, I completely agree on that. To be honest, I don't want hardcoded vendor software in this repository, I'd advocate for pip.
  
Otherwise, it's a great idea to use S-Parser, thanks for the contribution @ches.

**Comment by ches** [comment]
Okay, I've quickly removed the vendored `sexpdata` copy so that we can move past that point of discussion. This really should probably use `module_exists` and something like the `disable_plugin` machinery that is in `EnsimeClient` for a nicer user experience if the module isn't installed properly, but refactoring that to be usable to the launcher is something I'll have to come back to when I have a few more minutes to spare.

Updating docs to include the new pip install will have to be a separate pull request to the site repo when it's ready to be accepted, I guess. I'll squash commits on this branch when it's ready.

These todos are now reflected in the PR description.

**Comment by ches** [comment]
FWIW as long as it's only a couple or a few pip modules my suggestion is that we just advise `pip install websocket-client sexpdata` in the documentation, not introduce a requirements file that ordinary users need to be aware of—not all Vim users are familiar with details about Python packaging conventions, and we'll get into the mess of having to explain how the file path may differ between the umpteen plugin managers used across the Vim ecosystem 😩 

IMO the fewer particularities we need to explain that go beyond standard pure-VimL plugins, the better.

**Comment by ChrisCoffey** [comment]
Agreed, the more I thought about using a reqs file, the less I liked it. 

If you can update the documentation on the ensime page I'm happy to land this. Could you just cross-reference the documentation pull here?

**Comment by ChrisCoffey** [comment]
Made the doc change. Merging.

**Pull request merged**
