### PR TITLE
Introduce lettuce tests

### PR DESCRIPTION
**Pull request by ChrisCoffey**
This is the very beginnings of addressing #136. Here's an overview of the changes:

 - Removed all broken tests
 - Introduced Lettuce for Cucumber-style BDD tests
 - Implemented testing for config file parsing
 - Wired up to Drone

While Lettuce seems to be a fairly mature library, I'm worried that it isn't being that actively maintained (last commit Jan 2016). For what we're doing right now I think it's fine, but if we start running up against limitations we may want to switch to Aloe, an active fork.

I'm not convinced Lettuce will meet all of our test needs, so I'm open to adding in additional frameworks that fill any missing gaps.

I'm not a Python developer, so if anyone has advice on the correct way to do things here please jump right in & let me know.

### CODE REVIEW

**Comment by ChrisCoffey** [comment]
not sure why this isn't showing as completed, it finished 15 minutes ago on drone.

**Comment by jvican** [comment]
Good, let's wait until you have a significant test coverage and see how it evolves. Thanks for this, we really need it!

**Comment by ChrisCoffey** [comment]
@jvican would you mind elaborating a bit on why you'd like to grow this PR? Personally I feel the value of the broken tests is zero, so having a tiny amount of working coverage is better than a broad degree of broken coverage.

I can certainly be convinced to continue working in this PR, but I'm curious what your reasoning is.

**Comment by jvican** [comment]
Sure! I see it the other way around: there's no value in merging this into master if there are no real tests of ensime that, at least, test a significant part of the codebase for the upcoming PRs made by the community (>=30). The PRs that we are receiving are just fixes or new features and those wouldn't take advantage of a test suite until there's no actual test coverage.
  
Personally, I'd like to merge PRs that introduce concepts or features (e.g. a *basic* test suite is a whole feature). I just feel that splitting up an important feature into different PRs is wrong - it doesn't allow to keep track of its whole evolution. Instead, I'd prefer that you evolve this PR over time a little bit more. Note that I'm not asking you to have 80% coverage. It's just that what I see right now is a rough skeleton, just the test infrastructure, but not the actual test suite.

**Comment by ChrisCoffey** [comment]
Fair enough, this is just the rough skeleton. I'm comfortable saying we land this at 30% coverage.

**Comment by ChrisCoffey** [comment]
I'm closing this until I make more progress.

**Comment by ChrisCoffey** [comment]
I havn't had a chance to work on this lately, but reopening to help w/ #275

**Comment by jvican** [comment]
LGTM.

**Comment by ches** [comment]
It's great to get a start here. I'd been meaning to look at this PR and discuss for awhile, but just haven't had the bandwidth to work on the plugin or hang out in Gitter lately.

For what little I've been able to contribute my voice may not count for much, but here's two cents:

To me, a lot of the value of using an acceptance testing framework with a language-agnostic specification language would lie in getting buy-in from other editor plugin projects to have a shared test kit for common high-level feature support, sort of a compliance spec for baseline feature set that is widely deemed must-have. I believe that was @ChrisCoffey's idea reasoning for Lettuce early on.

It would surely take time to garner support for that idea, if it pans out at all, so naturally letting the inevitable inertia on that delay ensime-vim from having a test suite is no good.

That said, I would like to have a unit testing setup that will be less slow and cumbersome to run as it grows. It's just kinda weird to think about how it should work—on one hand, the *user interface* to ensime-vim is (n)Vim, including commands and other scriptable elements, so I'd like to actually test from that angle. But using one of the VimL test frameworks seems like it'd be painfully awkward when all the real code is Python. Maybe we'll eventually end up with a Python unit test suite as well as a light set of VimL tests.

Also, if there is any serious thought of trying to get other plugins on board with a shared test kit, we might want to consider a framework that supports standard Gherkin as closely as possible to have the best hope of interoperable specs. Maybe [behave][1] is worth a look? There might be others. Lettuce seems like it's really close, I just [can't find any solid statement][2].

It's really important to have *something* now, so 👍  (if that sounds at all demeaning of @ChrisCoffey's work, that's not intended). And Lettuce tests are good to have regardless, they get deep coverage, it's just the "testing pyramid" concerns I have for the longer term. So I wanted to bring up the subject of unit tests, in case anyone has opinions or preferred tools to express, etc. The PR is closed already but this seems as in-context as anywhere else… Gitter has the problem of being synchronous 😓 

[1]: https://pythonhosted.org/behave/index.html
[2]: https://github.com/gabrielfalcao/lettuce/issues/188

**Pull request merged**
