### PR TITLE
Fixes #356: Invoking completion after ( replaces the word that comes before

### LINKED ISSUE #356: Invoking completion after ( replaces the word that comes before
### Steps to reproduce

1. Check out https://github.com/jqno/EnsimeVimCompletionIssue
2. Open `CompletionTest.scala`
3. Write `print` and invoke completion; choose `println`.
4. Write `(`
5. Write `he` and invoke completion

### Expected behaviour

The line is expanded to `println(hello)`

### Actual behaviour

The line is expanded to `hello)`

### More info

I tried to fix this bug and offer a PR, but unfortunately I couldn't figure it out. I have noticed that `fun_en_complete_func` is invoked with a `base` parameter of `println(he`, where I would have expected just `he`. However, it seems to come directly from VIM that way, so I'm not sure what the intended approach should be:

* Try to get VIM to send `he` to ensime-vim instead of `println(he`
* Adapt ensime-vim to return `println(hello` instead of just `hello`
* Another approach entirely?

It seems to make sense to combine this with #271. I'd like to take a stab at that too, if you can give me some pointers :).

### PR DESCRIPTION
**Pull request by jqno**
Please see the discussion in issue #356.

### CODE REVIEW

**Comment by ktonga** [comment]
I'll merge this right away since the fix is really small and it solves a considerable bug.

**Comment by jvican** [comment]
Thank you for improving the quality of this plugin @jqno :tada:!

**Comment by ches** [comment]
Thanks for the fix @jqno, and for taking the trouble of creating a reproduction on the issue ticket!

**Comment by jqno** [comment]
You're welcome! 😃
I maintain an open source project myself, so I know how helpful it is to have a proper reproduction recipe. And your instructions to create one, were quite clear, so thanks for that!

**Pull request merged**
