### PR TITLE
Better completion formatting for methods. Fixes #273

### LINKED ISSUE #273: Completion: Several problems regarding type formatting
In the completion popup, specially for __functions__, the type hint may be ok for simple signatures, but it easily gets messy for complex ones. Here you have an example for `Seq.fill`:

What __Intellij Idea__ reports:
screen shot 2016-06-03 at 9 59 43 pm

What __ensime-vim__ reports:
screen shot 2016-06-03 at 9 18 01 pm

I can see a few problems so far:

- [x] Only the first entry is shown for overloaded functions (but all are present in server's response)
- [ ] Type parameters are not included at all
- [x] Only the first argument list is used
- [x] Fully qualified names are used which gets pretty unreadable

Now that ensime/ensime-server#1468 has been merged these problems seems quite simple to solve. I will start working on it and hopefully I'll be raising a PR in a few days.

### PR DESCRIPTION
**Pull request by ktonga**
- Show all overloaded methods
- Show all params sections
- Use short type names

See [this comment](https://github.com/ensime/ensime-vim/issues/273#issuecomment-224019333) for a reference screenshot.

### CODE REVIEW

**Comment by jvican** [comment]
This PR looks great! It would be awesome if you can add tests for it when the test suite is done. There's a closed PR introducing the new infrastructure, but it's not polished to go into master.
  
As for the PR, I find myself needing this very often. Thanks!

**Comment by ktonga** [comment]
@jvican Personally, this is the kind of feature I'd love to develop writing some property tests before starting with the implementation, the whole feature is a pure function `Completion => Suggestion`, and it was a pain to __modify + restart vim + trigger completion__ for each change I made.

What is the plan for @ChrisCoffey's PR? His branch seems to be getting outdated. I think it would be worth to create a branch for the new testing approach in the upstream repo to give it more visibility. People could target PRs to this branch to increase coverage so it eventually gets merged into master.

If this branch is created and my PR is merged into master I could raise a PR to add some test for the completion functionality to the testing branch.

My 2 cents.

**Comment by jvican** [comment]
Given the level of the importance of this issue, I'd be okay to merge the PR that @ChrisCoffey submitted some time ago. We could merge that if you are able to rebase and add more tests for this PR. Would that work for you, @ktonga ?

**Comment by ktonga** [comment]
@jvican Sure. Go ahead. I'll be able to add some tests in a coupe of days. Glad to hear that you considere this PR important :blush:

**Comment by ChrisCoffey** [comment]
That's an excellent idea. I'll reopen that PR shortly.

**Comment by jvican** [comment]
@ktonga You can now rebase and start writing the tests ;)

**Comment by ktonga** [comment]
@jvican @ChrisCoffey I've rebase and added some (a lot of) tests.

Please notice that I've refactored the code to move all format-related functions to a separate module to improve testability. I've also left some `TODO`s for improvements that are out-of-scope for this PR.

**Comment by ches** [comment]
LGTM!

This is great, and nice to see more "proof positive" of the new testing harness setup. Makes me feel a lot more confident that I can make more substantial changes without breaking things. I'll try to pitch in some further test coverage beyond the scope of this PR 😊

**Comment by ChrisCoffey** [comment]
LGTM! ran great locally & the code looks great. nice work @ktonga, thanks for the PR!

@jvican please take a look when you can.

**Comment by jvican** [comment]
Let's merge this, thanks again @ktonga :smile:

**Pull request merged**
