### PR TITLE
Autocomplete causes screen flickering

### PR DESCRIPTION
**Pull request by neg-serg**
Add ":silent!" and redraw fix annoying messages caused by execution of external script. Always use it when user are not interested in command output.

### CODE REVIEW

**Comment by ChrisCoffey** [comment]
Thanks! You're running Vim not NeoVim, correct?

Please squash your commits & begin the commit message with a capital letter.

**Comment by neg-serg** [comment]
Ok, as far as I see I've fixed it.

Yes, it is. I am using legacy vim for now, because of neovim has a bunch of UX issues for me at this moment.

**Comment by jvican** [comment]
Hey @ChrisCoffey, let's wait until we two LGTM code before merging. We could follow this strategy for any PR that it's not ours. This way we avoid confusions in case one of us is actually working on something that PR addresses.

**Comment by ChrisCoffey** [comment]
@jvican sounds great to me. Feel free to revert this if you're taking a different approach with it!

**Comment by jvican** [comment]
No, it's fine :+1: I'm just proposing to use a default strategy to deal with new PRs so that both of us agree on the quality of the PR.

**Comment by jvican** [comment]
BTW, thanks @neg-serg for this fix, very useful!

**Pull request merged**
